# Generated by Django 5.2.8 on 2025-11-16 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(default='system', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_seen', models.DateTimeField(blank=True, null=True)),
                ('composite_key', models.CharField(blank=True, db_index=True, max_length=512)),
                ('composite_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('intent', models.CharField(choices=[('LISTING', 'Listing'), ('REQUIREMENT', 'Requirement'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('transaction_type', models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale'), ('LEASE', 'Lease'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_chunks', to='ingestion.rawmessagechunk')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('vector_db_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_index_name', models.CharField(blank=True, max_length=128, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('listing_chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='preprocessing.listingchunk')),
            ],
        ),
        migrations.AddIndex(
            model_name='listingchunk',
            index=models.Index(fields=['composite_hash'], name='preproc_comphash_idx'),
        ),
        migrations.AddIndex(
            model_name='listingchunk',
            index=models.Index(fields=['last_seen'], name='preproc_lastseen_idx'),
        ),
    ]
