# Generated by Django 5.2.8 on 2025-11-27 16:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0005_create_hsnw_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingrecord',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, db_column='embedding_vector_v', dimensions=1536, null=True),
        ),
    ]
