# Generated by Django 5.2.8 on 2025-12-08 02:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0006_alter_embeddingrecord_embedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingrecord',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
