# Generated by Django 5.2.8 on 2025-11-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('bhk', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('vector_cache', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='core_listin_locatio_f5544e_idx'), models.Index(fields=['price'], name='core_listin_price_6e330c_idx')],
            },
        ),
    ]
