# Generated by Django 5.2.8 on 2025-11-23 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listingchunk_delete_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingchunk',
            old_name='bathrooms',
            new_name='bhk',
        ),
        migrations.RenameField(
            model_name='listingchunk',
            old_name='area',
            new_name='building_name',
        ),
        migrations.RenameField(
            model_name='listingchunk',
            old_name='text',
            new_name='cleaned_text',
        ),
        migrations.RenameField(
            model_name='listingchunk',
            old_name='city',
            new_name='furnishing',
        ),
        migrations.RenameField(
            model_name='listingchunk',
            old_name='rent',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='listingchunk',
            old_name='bedrooms',
            new_name='sqft',
        ),
        migrations.AddField(
            model_name='listingchunk',
            name='contact_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='listingchunk',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='listingchunk',
            name='listing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingchunk',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingchunk',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listingchunk',
            name='parking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
