# Generated by Django 5.2.8 on 2025-11-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raw_chats/')),
                ('file_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('process_started_at', models.DateTimeField(blank=True, null=True)),
                ('process_finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMessageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_start', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('split_into', models.IntegerField(default=0)),
                ('status', models.CharField(default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rawfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_chunks', to='ingestion.rawfile')),
            ],
        ),
    ]
