# Generated by Django 5.2.8 on 2025-11-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
