"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import ssl

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SECURITY CONFIGURATION ---

# Keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-fallback-dev-key")

# FIX: Compare String to String. "True" == "True" is True.
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    'whatsapp-parser-tool.onrender.com',
    'bandrahomes.in',
    'www.bandrahomes.in', 
    'localhost', 
    '127.0.0.1'
]

# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'pgvector',
    'apps.core',
    'apps.ingestion',
    'apps.preprocessing',
    'apps.embeddings',
    'apps.users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGIN_URL = "/users/login/"
LOGIN_REDIRECT_URL = "/core/chat/"     
LOGOUT_REDIRECT_URL = "/users/login/"

WSGI_APPLICATION = 'config.wsgi.application'


# --- DATABASE CONFIGURATION ---
# Uses Environment variables if available (Prod), falls back to localhost defaults (Dev)

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME", "whatsapp-parser-tool-db"),
        'USER': os.getenv("DB_USER", "postgres"),
        'PASSWORD': os.getenv("DB_PASS", "admin@2025"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
        'POOL_MODE': 'transaction',
        'CONN_MAX_AGE': 30,
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}
"""


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'whatsapp-parser-tool-db',
        'USER': 'postgres',
        'PASSWORD': 'admin@2025',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Add SSL options only if we are in Production/Remote DB context
if not DEBUG and os.getenv("DB_HOST") not in ['localhost', '127.0.0.1']:
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'options': '-c search_path=public',
    }


# --- REDIS & CELERY CONFIGURATION ---

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')

# 1. Base Settings (Local / No-SSL)
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_BROKER_USE_SSL = False
CELERY_REDIS_BACKEND_USE_SSL = False

CELERY_WORKER_CONCURRENCY = 16
# Prevent worker from prefetching too many tasks (fair distribution)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Disable result backend to save Redis Ops (critical for 10k daily limit)
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Note: CONNECTION_POOL_KWARGS is intentionally missing here for Local dev
        }
    }
}

# 2. Production / SSL Overrides
# Only apply SSL settings if DEBUG is False AND the URL supports it
if not DEBUG and REDIS_URL.startswith("rediss://"):
    
    # Fix URL query params for Celery
    if "?" not in REDIS_URL:
        REDIS_URL += "?ssl_cert_reqs=none"
    elif "ssl_cert_reqs" not in REDIS_URL:
        REDIS_URL += "&ssl_cert_reqs=none"
        
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    
    ssl_conf = {'ssl_cert_reqs': ssl.CERT_NONE}
    CELERY_BROKER_USE_SSL = ssl_conf
    CELERY_REDIS_BACKEND_USE_SSL = ssl_conf
    
    # Inject SSL args into Cache config
    CACHES["default"]["OPTIONS"]["CONNECTION_POOL_KWARGS"] = {
        "ssl_cert_reqs": ssl.CERT_NONE
    }


# --- PASSWORD VALIDATION ---

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- INTERNATIONALIZATION ---

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- STATIC & MEDIA ---

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)


# --- MISC ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# --- SECURITY & HTTPS ---

# Always needed for Render/Vercel
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    "https://whatsapp-parser-tool.onrender.com",
    "https://localhost",
    "https://127.0.0.1",
]

if DEBUG:
    # Local Development Settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_HSTS_SECONDS = 0
    
    # Allow local HTTP origins
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:8001",
        "http://127.0.0.1:8001",
    ]
else:
    # Production Settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True